development:
  adapter: postgresql
  encoding: unicode
  database: descuentos_development
  pool: 5
  username: forcegrid
  password: ''

test:
  adapter: postgresql
  encoding: unicode
  database: descuentos_test
  pool: 5
  username: forcegrid
  password: ''

production:
  adapter: postgresql
  encoding: unicode
  database: descuentos_production
  pool: 5
  username: forcegrid
  password: ''